### ISSUE TITLE
NPM package validation failing for certain packages

### ISSUE THREAD

**Issue by domdomegg** [modelcontextprotocol/registry#409]
From Discord:

> I'm trying to publish my MCP server and it is not working. 
>
> Error: publish failed: server returned status 400: {"title":"Bad Request","status":400,"detail":"Failed to publish server","errors":[{"message":"registry validation failed for package 0 (@hellocoop/admin-mcp): NPM package '@hellocoop/admin-mcp' not found (status: 404)"}]}

**Comment by domdomegg** [comment]
My initial guess is that maybe it's something about the URL encoding etc, given the `@` and `/` symbols? Not sure we have tests for namespaced servers, which we should.

**Comment by Avish34** [comment]
@domdomegg  I will also try to check this. We certainly need to add more test cases :)

**Comment by dickhardt** [comment]
@hellocoop/admin-mcp is the NPM package name 

Let me know what I can do to help debug

**Comment by Avish34** [comment]
@dickhardt can you please help me with your server.json that you used to publish? I need to find what's going wrong.

**Comment by dickhardt** [comment]
```json
{
  "$schema": "https://static.modelcontextprotocol.io/schemas/2025-07-09/server.schema.json",
  "name": "io.github.hellocoop/admin-mcp",
  "description": "Model Context Protocol (MCP) for Hellō Admin API.",
  "status": "active",
  "repository": {
    "url": "https://github.com/hellocoop/admin-mcp",
    "source": "github"
  },
  "version": "1.0.0",
  "packages": [
    {
      "registry_type": "npm",
      "registry_base_url": "https://registry.npmjs.org",
      "identifier": "@hellocoop/admin-mcp",
      "version": "1.0.0",
      "transport": {
        "type": "stdio"
      }
    }
  ]
}
```

**Comment by dickhardt** [comment]
repo is public

https://github.com/hellocoop/admin-mcp

**Comment by dickhardt** [comment]
I just tried to publish again and got the same error 

I do:
`mcp-publisher login github`
Then:
`mcp-publisher publish`

and get
```
Publishing to https://registry.modelcontextprotocol.io...
Error: publish failed: server returned status 400: {"title":"Bad Request","status":400,"detail":"Failed to publish server","errors":[{"message":"registry validation failed for package 0 (@hellocoop/admin-mcp): NPM package '@hellocoop/admin-mcp' not found (status: 404)"}]}
```

**Comment by domdomegg** [comment]
Think this should be fixed by https://github.com/modelcontextprotocol/registry/pull/429

**Comment by A1996-dot** [comment]
{
  "$schema": "https://static.modelcontextprotocol.io/schemas/2025-07-09/server.schema.json",
  "name": "io.github.hellocoop/admin-mcp",
  "description": "Model Context Protocol (MCP) for Hellō Admin API.",
  "status": "active",
  "repository": {
    "url": "https://github.com/hellocoop/admin-mcp",
    "source": "github"
  },
  "version": "1.0.0",
  "packages": [
    {
      "registry_type": "npm",
      "registry_base_url": "https://registry.npmjs.org",
      "identifier": "@hellocoop/admin-mcp",
      "version": "1.0.0",
      "transport": {
        "type": "studio"
      }
    }
  ]
}
some error i find than i do correction

**Comment by dickhardt** [comment]
> Think this should be fixed by [#429](https://github.com/modelcontextprotocol/registry/pull/429)

I just tried again. Same error. Is fix deployed?

**Comment by domdomegg** [comment]
@dickhardt sorry, just merged now! Should be deployed in the next 15 minutes or so.

**Comment by dickhardt** [comment]
@domdomegg -- just tried again -- same error

**Comment by domdomegg** [comment]
Heya! After looking into this more I think registry does seem to be working correctly for scoped NPM packages now.

E.g. https://registry.modelcontextprotocol.io/v0/servers?search=io.github.florentine-ai/mcp is one such example.

I think there might be the issue with your server being published is that version 1.0.0 isn't actually published to NPM, which is resulting in the 404 error. This is the version you listed in your server.json that you shared with us. I think you might instead want to use version 1.5.7:

```diff
{
  "$schema": "https://static.modelcontextprotocol.io/schemas/2025-07-09/server.schema.json",
  "name": "io.github.hellocoop/admin-mcp",
  "description": "Model Context Protocol (MCP) for Hellō Admin API.",
  "status": "active",
  "repository": {
    "url": "https://github.com/hellocoop/admin-mcp",
    "source": "github"
  },
@@ potentially you also want to update this version, although you don't have to it's generally recommend to keep the registry entry version aligned with the package version to avoid confusion @@
  "version": "1.0.0",
  "packages": [
    {
      "registry_type": "npm",
      "registry_base_url": "https://registry.npmjs.org",
      "identifier": "@hellocoop/admin-mcp",
+      "version": "1.5.7",
-      "version": "1.0.0",
      "transport": {
        "type": "stdio"
      }
    }
  ]
}
```

**Comment by domdomegg** [comment]
If you're using version 1.5.7 and it still doesn't work with the same error do let us know! When testing locally this seems to pass the validation checks for me :)

**Comment by dickhardt** [comment]
Published now. I created a PR to tell others to update the version. https://github.com/modelcontextprotocol/registry/pull/462

**Comment by domdomegg** [comment]
Awesome! Will give that a review later
